import { Metadata } from "next"
import { Kanit } from "next/font/google"


const kanit = Kanit({ weight:['100','200','300','400','500','600','700']})

export const metadata: Metadata = {
  title: 'AWS-NBHospital',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
       <div>
         <h3>header About</h3> <hr />
        {children} 
        
       </div>
   
  )
}
