import type { Metadata } from 'next'
import { Inter, Kanit } from 'next/font/google'
import '../globals.css'
import Providers from '@/components/Providers'
import DLayout from "./components/DLayout"

const kanit = Kanit({ weight:['100','200','300','400','500','600','700'],subsets: ['latin']})

export const metadata: Metadata = {
  title: 'NBHospital-Dashboard',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <DLayout>{children} </DLayout>
      
      </Providers>
        </body>
    </html>
  )
}
