import type { Metadata } from 'next'
import { Inter, Kanit } from 'next/font/google'
import '../globals.css'

const kanit = Kanit({ weight:['100','200','300','400','500','600','700'],subsets: ['latin']})

export const metadata: Metadata = {
  title: 'NBHospital-Dashboard',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <h1>Dashboard-header</h1> <hr />
        {children} <hr />
        <h4>Dashboard-footer</h4>
        </body>
    </html>
  )
}
