"use client";

// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import '@mantine/core/styles.css';

import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { Kanit } from 'next/font/google';
import { Metadata } from 'next';


const kanit = Kanit({ weight:['100','200','300','400','500','600','700'],subsets: ['latin']})

export const metadata: Metadata = {
  title: 'NBHospital-Dashboard',
  description: 'Generated by create next app',
}
export default function providers({ children }: { children: React.ReactNode }) {
  return (
    
      <body>
        <MantineProvider theme={{fontFamily:kanit.style.fontFamily}}>
            {children}
        </MantineProvider>
      </body>
    
  );
}